---
branches:
  only:
    - master

language: python
cache: pip

install:
  - pip install -r dev-requirements.txt.lock

jobs:
  include:
    - stage: 'Lint and Unit Tests'
      name: 'py27'
      python: '2.7'
      env: 'TOXENV=py27'
      script: tox
    - name: 'py34'
      python: '3.4'
      env: 'TOXENV=py34'
      script: tox
    - name: 'shell'
      sudo: required
      services:
        - docker
      install: ''
      script: make shell-lint

    - stage: 'Func tests'
      name: 'Build container image and run func-tests'
      services:
        - docker
      before_install:
        - sudo apt-get install -y realpath
      script:
        - make container
        - make func-test IMAGE="$(make container-static-version)"
      deploy:
        provider: script
        script: echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin quay.io && make push-container
        on:
          branch: master
