---
branches:
  only:
    - master

language: python
cache: pip
matrix:
  include:
    - python: '2.7'
      env: 'TOXENV=py27'
    - python: '3.4'
      env: 'TOXENV=py34'

install:
  - pip install -r dev-requirements.txt.lock

jobs:
  include:
    - stage: 'Python tests'
      name: 'Tox'
      script: tox
    - stage: 'Docker'
      sudo: required
      services:
        - docker
      script:
        - make container
        - make func-test IMAGE="$(make container-static-version)"
      deploy:
        provider: script
        script: echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin quay.io && make push-container
        on:
          branch: master
